// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfyiqedyesexxflbmhou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmeWlxZWR5ZXNleHhmbGJtaG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODU4NzEsImV4cCI6MjA1NjQ2MTg3MX0.G9NCmOMnB_K97AXxNYWI7dbJReTi6qh84elhHBnyFqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);